USE drinkdb;
DROP TABLE IF EXISTS tbl_drink;
DROP TABLE IF EXISTS tbl_category;

CREATE TABLE IF NOT EXISTS tbl_category (
	CATEGORY_CODE INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(5) NOT NULL UNIQUE
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS tbl_drink (
	DRINK_CODE INT PRIMARY KEY AUTO_INCREMENT,
    DRINK_NAME VARCHAR(15) NOT NULL UNIQUE,
    DRINK_PRICE INT NOT NULL,
    CATEGORY_CODE INT NOT NULL,
    FOREIGN KEY(CATEGORY_CODE) REFERENCES tbl_category(CATEGORY_CODE)
) ENGINE = INNODB;